<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas</name>
   <tag></tag>
   <elementGuidId>65376c0d-b7fc-414f-ba92-e3ca50114e4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>365</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>91.25</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-home[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content&quot;]/app-chatbot[@class=&quot;ng-tns-c2-0&quot;]/div[@class=&quot;ng-tns-c2-0&quot;]/div[@class=&quot;bot-position ng-trigger ng-trigger-enterAnimation&quot;]/div[@class=&quot;chatbot px-3 py-4 ng-tns-c2-0 ng-star-inserted&quot;]/div[@class=&quot;chatbot__conversation&quot;]/div[@class=&quot;ng-tns-c2-0 ng-star-inserted&quot;]/div[@class=&quot;chatbot__chat bot ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c2-0 ng-star-inserted&quot;]/ng-signature-pad[@class=&quot;ng-tns-c2-0&quot;]/div[@class=&quot;signature-pad&quot;]/canvas[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
   </webElementXpaths>
</WebElementEntity>
